API_KEY = 'AIzaSyCome9MA6HFIVVZtQJy5Do8YQtOBvArgb0'
DEFAULT_DATASET_SIZE = 10000
DEFAULT_IMAGE_SIZE = '640x640'
DEFAULT_FOV = 120
STREETVIEW_API_BASE_URL = 'https://maps.googleapis.com/maps/api/streetview'